services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Security\LoginSuccessHandler:
        arguments:
            $router: '@router'

parameters:
    artist_images_directory: '%kernel.project_dir%/public/uploads/artists'
